#!/usr/bin/env bash
# Display numbers from 1 to 20 with special messages

# Initialize counter
counter=1

# Execute while counter is less than or equal to 20
while [ $counter -le 20 ]; do
    # Display numbers from 1 to 20
    echo $counter

    # Check for special iterations
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac

    # Increment counter
    ((counter++))
done
